/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GeneratingRouteImport } from './routes/generating'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as IndexRouteImport } from './routes/index'

const GeneratingRoute = GeneratingRouteImport.update({
  id: '/generating',
  path: '/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/generating': typeof GeneratingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/generating': typeof GeneratingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/generating': typeof GeneratingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/confirm' | '/generating'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/confirm' | '/generating'
  id: '__root__' | '/' | '/confirm' | '/generating'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmRoute: typeof ConfirmRoute
  GeneratingRoute: typeof GeneratingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/generating': {
      id: '/generating'
      path: '/generating'
      fullPath: '/generating'
      preLoaderRoute: typeof GeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmRoute: ConfirmRoute,
  GeneratingRoute: GeneratingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
