/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GeneratingRouteImport } from './routes/generating'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIdRouteImport } from './routes/results.$id'
import { Route as ConnectInstagramRouteImport } from './routes/connect.instagram'
import { Route as BlogFlatLayGuideRouteImport } from './routes/blog.flat-lay-guide'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedProfileRouteRouteImport } from './routes/_authenticated/profile/route'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicMetaOauthCallbackRouteImport } from './routes/api/public/meta-oauth-callback'
import { Route as AuthenticatedProfileAccountRouteImport } from './routes/_authenticated/profile/account'
import { Route as AuthenticatedAdminCostsRouteImport } from './routes/_authenticated.admin.costs'

const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratingRoute = GeneratingRouteImport.update({
  id: '/generating',
  path: '/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectInstagramRoute = ConnectInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => ConnectRoute,
} as any)
const BlogFlatLayGuideRoute = BlogFlatLayGuideRouteImport.update({
  id: '/blog/flat-lay-guide',
  path: '/blog/flat-lay-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedProfileRouteRoute =
  AuthenticatedProfileRouteRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileRouteRoute,
  } as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaOauthCallbackRoute =
  ApiPublicMetaOauthCallbackRouteImport.update({
    id: '/api/public/meta-oauth-callback',
    path: '/api/public/meta-oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProfileAccountRoute =
  AuthenticatedProfileAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedProfileRouteRoute,
  } as any)
const AuthenticatedAdminCostsRoute = AuthenticatedAdminCostsRouteImport.update({
  id: '/admin/costs',
  path: '/admin/costs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/billing': typeof BillingRoute
  '/brand-kit': typeof BrandKitRoute
  '/calendar': typeof CalendarRoute
  '/confirm': typeof ConfirmRoute
  '/connect': typeof ConnectRouteWithChildren
  '/create': typeof CreateRoute
  '/generating': typeof GeneratingRoute
  '/how-it-works': typeof HowItWorksRoute
  '/library': typeof LibraryRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stock': typeof StockRoute
  '/profile': typeof AuthenticatedProfileRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/flat-lay-guide': typeof BlogFlatLayGuideRoute
  '/connect/instagram': typeof ConnectInstagramRoute
  '/results/$id': typeof ResultsIdRoute
  '/admin/costs': typeof AuthenticatedAdminCostsRoute
  '/profile/account': typeof AuthenticatedProfileAccountRoute
  '/api/public/meta-oauth-callback': typeof ApiPublicMetaOauthCallbackRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/billing': typeof BillingRoute
  '/brand-kit': typeof BrandKitRoute
  '/calendar': typeof CalendarRoute
  '/confirm': typeof ConfirmRoute
  '/connect': typeof ConnectRouteWithChildren
  '/create': typeof CreateRoute
  '/generating': typeof GeneratingRoute
  '/how-it-works': typeof HowItWorksRoute
  '/library': typeof LibraryRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stock': typeof StockRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/flat-lay-guide': typeof BlogFlatLayGuideRoute
  '/connect/instagram': typeof ConnectInstagramRoute
  '/results/$id': typeof ResultsIdRoute
  '/admin/costs': typeof AuthenticatedAdminCostsRoute
  '/profile/account': typeof AuthenticatedProfileAccountRoute
  '/api/public/meta-oauth-callback': typeof ApiPublicMetaOauthCallbackRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/billing': typeof BillingRoute
  '/brand-kit': typeof BrandKitRoute
  '/calendar': typeof CalendarRoute
  '/confirm': typeof ConfirmRoute
  '/connect': typeof ConnectRouteWithChildren
  '/create': typeof CreateRoute
  '/generating': typeof GeneratingRoute
  '/how-it-works': typeof HowItWorksRoute
  '/library': typeof LibraryRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stock': typeof StockRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/flat-lay-guide': typeof BlogFlatLayGuideRoute
  '/connect/instagram': typeof ConnectInstagramRoute
  '/results/$id': typeof ResultsIdRoute
  '/_authenticated/admin/costs': typeof AuthenticatedAdminCostsRoute
  '/_authenticated/profile/account': typeof AuthenticatedProfileAccountRoute
  '/api/public/meta-oauth-callback': typeof ApiPublicMetaOauthCallbackRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/billing'
    | '/brand-kit'
    | '/calendar'
    | '/confirm'
    | '/connect'
    | '/create'
    | '/generating'
    | '/how-it-works'
    | '/library'
    | '/pricing'
    | '/sitemap.xml'
    | '/stock'
    | '/profile'
    | '/auth/callback'
    | '/blog/flat-lay-guide'
    | '/connect/instagram'
    | '/results/$id'
    | '/admin/costs'
    | '/profile/account'
    | '/api/public/meta-oauth-callback'
    | '/api/public/razorpay-webhook'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/billing'
    | '/brand-kit'
    | '/calendar'
    | '/confirm'
    | '/connect'
    | '/create'
    | '/generating'
    | '/how-it-works'
    | '/library'
    | '/pricing'
    | '/sitemap.xml'
    | '/stock'
    | '/auth/callback'
    | '/blog/flat-lay-guide'
    | '/connect/instagram'
    | '/results/$id'
    | '/admin/costs'
    | '/profile/account'
    | '/api/public/meta-oauth-callback'
    | '/api/public/razorpay-webhook'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/billing'
    | '/brand-kit'
    | '/calendar'
    | '/confirm'
    | '/connect'
    | '/create'
    | '/generating'
    | '/how-it-works'
    | '/library'
    | '/pricing'
    | '/sitemap.xml'
    | '/stock'
    | '/_authenticated/profile'
    | '/auth/callback'
    | '/blog/flat-lay-guide'
    | '/connect/instagram'
    | '/results/$id'
    | '/_authenticated/admin/costs'
    | '/_authenticated/profile/account'
    | '/api/public/meta-oauth-callback'
    | '/api/public/razorpay-webhook'
    | '/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BillingRoute: typeof BillingRoute
  BrandKitRoute: typeof BrandKitRoute
  CalendarRoute: typeof CalendarRoute
  ConfirmRoute: typeof ConfirmRoute
  ConnectRoute: typeof ConnectRouteWithChildren
  CreateRoute: typeof CreateRoute
  GeneratingRoute: typeof GeneratingRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LibraryRoute: typeof LibraryRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StockRoute: typeof StockRoute
  BlogFlatLayGuideRoute: typeof BlogFlatLayGuideRoute
  ResultsIdRoute: typeof ResultsIdRoute
  ApiPublicMetaOauthCallbackRoute: typeof ApiPublicMetaOauthCallbackRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generating': {
      id: '/generating'
      path: '/generating'
      fullPath: '/generating'
      preLoaderRoute: typeof GeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/instagram': {
      id: '/connect/instagram'
      path: '/instagram'
      fullPath: '/connect/instagram'
      preLoaderRoute: typeof ConnectInstagramRouteImport
      parentRoute: typeof ConnectRoute
    }
    '/blog/flat-lay-guide': {
      id: '/blog/flat-lay-guide'
      path: '/blog/flat-lay-guide'
      fullPath: '/blog/flat-lay-guide'
      preLoaderRoute: typeof BlogFlatLayGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedProfileRouteRoute
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-oauth-callback': {
      id: '/api/public/meta-oauth-callback'
      path: '/api/public/meta-oauth-callback'
      fullPath: '/api/public/meta-oauth-callback'
      preLoaderRoute: typeof ApiPublicMetaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/account': {
      id: '/_authenticated/profile/account'
      path: '/account'
      fullPath: '/profile/account'
      preLoaderRoute: typeof AuthenticatedProfileAccountRouteImport
      parentRoute: typeof AuthenticatedProfileRouteRoute
    }
    '/_authenticated/admin/costs': {
      id: '/_authenticated/admin/costs'
      path: '/admin/costs'
      fullPath: '/admin/costs'
      preLoaderRoute: typeof AuthenticatedAdminCostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedProfileRouteRouteChildren {
  AuthenticatedProfileAccountRoute: typeof AuthenticatedProfileAccountRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteRouteChildren: AuthenticatedProfileRouteRouteChildren =
  {
    AuthenticatedProfileAccountRoute: AuthenticatedProfileAccountRoute,
    AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  }

const AuthenticatedProfileRouteRouteWithChildren =
  AuthenticatedProfileRouteRoute._addFileChildren(
    AuthenticatedProfileRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRouteRoute: typeof AuthenticatedProfileRouteRouteWithChildren
  AuthenticatedAdminCostsRoute: typeof AuthenticatedAdminCostsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRouteRoute: AuthenticatedProfileRouteRouteWithChildren,
  AuthenticatedAdminCostsRoute: AuthenticatedAdminCostsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ConnectRouteChildren {
  ConnectInstagramRoute: typeof ConnectInstagramRoute
}

const ConnectRouteChildren: ConnectRouteChildren = {
  ConnectInstagramRoute: ConnectInstagramRoute,
}

const ConnectRouteWithChildren =
  ConnectRoute._addFileChildren(ConnectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BillingRoute: BillingRoute,
  BrandKitRoute: BrandKitRoute,
  CalendarRoute: CalendarRoute,
  ConfirmRoute: ConfirmRoute,
  ConnectRoute: ConnectRouteWithChildren,
  CreateRoute: CreateRoute,
  GeneratingRoute: GeneratingRoute,
  HowItWorksRoute: HowItWorksRoute,
  LibraryRoute: LibraryRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StockRoute: StockRoute,
  BlogFlatLayGuideRoute: BlogFlatLayGuideRoute,
  ResultsIdRoute: ResultsIdRoute,
  ApiPublicMetaOauthCallbackRoute: ApiPublicMetaOauthCallbackRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
