/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GeneratingRouteImport } from './routes/generating'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIdRouteImport } from './routes/results.$id'
import { Route as BlogFlatLayGuideRouteImport } from './routes/blog.flat-lay-guide'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratingRoute = GeneratingRouteImport.update({
  id: '/generating',
  path: '/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogFlatLayGuideRoute = BlogFlatLayGuideRouteImport.update({
  id: '/blog/flat-lay-guide',
  path: '/blog/flat-lay-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/brand-kit': typeof BrandKitRoute
  '/calendar': typeof CalendarRoute
  '/confirm': typeof ConfirmRoute
  '/generating': typeof GeneratingRoute
  '/library': typeof LibraryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/flat-lay-guide': typeof BlogFlatLayGuideRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/brand-kit': typeof BrandKitRoute
  '/calendar': typeof CalendarRoute
  '/confirm': typeof ConfirmRoute
  '/generating': typeof GeneratingRoute
  '/library': typeof LibraryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/flat-lay-guide': typeof BlogFlatLayGuideRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/brand-kit': typeof BrandKitRoute
  '/calendar': typeof CalendarRoute
  '/confirm': typeof ConfirmRoute
  '/generating': typeof GeneratingRoute
  '/library': typeof LibraryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/flat-lay-guide': typeof BlogFlatLayGuideRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/brand-kit'
    | '/calendar'
    | '/confirm'
    | '/generating'
    | '/library'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/blog/flat-lay-guide'
    | '/results/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/brand-kit'
    | '/calendar'
    | '/confirm'
    | '/generating'
    | '/library'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/blog/flat-lay-guide'
    | '/results/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/brand-kit'
    | '/calendar'
    | '/confirm'
    | '/generating'
    | '/library'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/blog/flat-lay-guide'
    | '/results/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  BrandKitRoute: typeof BrandKitRoute
  CalendarRoute: typeof CalendarRoute
  ConfirmRoute: typeof ConfirmRoute
  GeneratingRoute: typeof GeneratingRoute
  LibraryRoute: typeof LibraryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogFlatLayGuideRoute: typeof BlogFlatLayGuideRoute
  ResultsIdRoute: typeof ResultsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generating': {
      id: '/generating'
      path: '/generating'
      fullPath: '/generating'
      preLoaderRoute: typeof GeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/flat-lay-guide': {
      id: '/blog/flat-lay-guide'
      path: '/blog/flat-lay-guide'
      fullPath: '/blog/flat-lay-guide'
      preLoaderRoute: typeof BlogFlatLayGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  BrandKitRoute: BrandKitRoute,
  CalendarRoute: CalendarRoute,
  ConfirmRoute: ConfirmRoute,
  GeneratingRoute: GeneratingRoute,
  LibraryRoute: LibraryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogFlatLayGuideRoute: BlogFlatLayGuideRoute,
  ResultsIdRoute: ResultsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
